Innovators/Models/Quiz.cs
namespace Innovators.Models
{
    public class Quiz
    {
        public int QuizId { get; set; }
        public string Excecise { get; set; }
        public string Q1 { get; set; }
        public string Q2 { get; set; }

        public string Q3 { get; set; }

        public string Q4 { get; set; }

        public string Q5 { get; set; }
        public int Grade { get; set; }

        public string Memo1 { get; set; }
        public string Memo2 { get; set; }

        public string Memo3 { get; set; }

        public string Memo4 { get; set; }

        public string Memo5 { get; set; }

        public string A1 { get; set; }
        public string A2 { get; set; }

        public string A3 { get; set; }

        public string A4 { get; set; }

        public string A5 { get; set; }
        public int Total { get; set; }




    }
}

Innovators/Controllers/LecturerController.cs
using Innovators.Data;
using Innovators.Migrations;
using Innovators.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace Innovators.Controllers
{
    public class LecturerController : Controller
    {
        private readonly TaskDbContext _db;
       

        public LecturerController(TaskDbContext db)
        {
            _db = db;
        }
      
        //lending
        
        
       
        public IActionResult Index()
        {
            IEnumerable<Task> obj = _db.Task; //from database


            return View(obj);
           
        }
        [HttpGet]
        public IActionResult Login()
        {
            Users _users = new Users();
            return View(_users);
        }
        
        [HttpPost]
        public IActionResult Login(Users _users)
        {
            UserDbContext _db=new UserDbContext();  
           
           var status=_db.Users.Where(m=>m.Email==_users.Email && m.Password==_users.Password).FirstOrDefault();   
           if(status==null)
            {
                ViewBag.LoginStatus = 0;
            }
           else
            {
                return RedirectToAction("Success", "Lecturer");
            }
            return View(_db);
        }
        public IActionResult Success()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateTask(Task obj)
        {
            _db.Task.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
            
        }

        
        public IActionResult UpdateTask(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Task.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);

            
        }



        [HttpPost]
        public IActionResult DeleteTask(int? id)
        {
            return View();
        }

        public IActionResult CreateTask(Task obj)
        {
            if (ModelState.IsValid)//Checks to see if all the required fields have been met.
            {
                _db.Task.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }


      
       
            
        
    }
}

Innovators/Controllers/QuizController.cs
using Innovators.Data;
using Innovators.Migrations.QuizDb;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Innovators.Models;

namespace Innovators.Controllers
{
    public class QuizController : Controller
    {
        private readonly QuizModelDbContext _db;
        public QuizController(QuizModelDbContext db)
        {
            _db = db;
        }
        public IActionResult Live()
        {

            return View();
        }
        public IActionResult Memo()
        {

            IEnumerable<QuizModel> obj = _db.QuizModel;

            return View(obj);  
        }
        [HttpGet]
        public IActionResult QuizCreate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult QuizCreate(QuizModel obj)
        {
            if (ModelState.IsValid)//Checks to see if all the required fields have been met.
            {
                _db.QuizModel.Add(obj); 
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
            
        }

        public IActionResult Index()
        {
            IEnumerable<QuizModel> obj = _db.QuizModel;



            return View(obj);
        }
    }
}

Innovators/Controllers/RegisterController.cs
using Innovators.Data;
using Innovators.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Innovators.Controllers
{
    public class RegisterController : Controller
    {
        private readonly RegisterDbContext _db;

        public RegisterController(RegisterDbContext db)
        {
            _db = db;
        }
    
        public IActionResult Index()
        {
            IEnumerable<Register> obj = _db.Register; 

            return View(obj);
        }
        [HttpGet]
        public IActionResult CreateRegister()
        {
            return View();
        }

        public IActionResult Report()
        {
            IEnumerable<Register> obj = _db.Register;

            return View(obj);
        }
        [HttpPost]
        public IActionResult CreateRegister(Register obj)
        {
            if (ModelState.IsValid)//Checks to see if all the required fields have been met.
            {
                _db.Register.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }





        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Report(Register obj)
        //{
        //    _db.Register.Update(obj);
        //    _db.SaveChanges();
        //    return RedirectToAction("Index");

        //}

        //[HttpGet]
        //public IActionResult Report(int? id)
        //{
        //    if (id == null || id == 0)
        //    {
        //        return NotFound();
        //    }

        //    var obj = _db.Register.Find(id);
        //    if (obj == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(obj);


        //}


    }
}

Innovators/Views/Lecturer/CreateTask.cshtml
@model Innovators.Models.Task 


<form enctype="multipart/form-data" method="post" asp-action="CreateTask">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Task</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="TaskName"></label>@*These names come from our properties in the model *@
                    </div>
                    <div class="col-6">
                        <label asp-for="TaskDescription"></label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="TaskName" class="form-control" />
                        <span asp-validation-for="TaskName" class="text-danger"></span>

                    </div>
                    <div class="col-6">
                        <input asp-for="TaskDescription" class="form-control" />
                        <span asp-validation-for="TaskDescription" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="CreateTask" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>


        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="SetDate"></label>@*These names come from our properties in the model *@
                    </div>
                    <div class="col-6">
                        <label asp-for="DueDate"></label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="SetDate" class="form-control" />
                        <span asp-validation-for="SetDate" class="text-danger"></span>

                    </div>
                    <div class="col-6">
                        <input asp-for="DueDate" class="form-control" />
                        <span asp-validation-for="DueDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>




@*
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroupFileAddon01"></span>
            </div>
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="inputGroupFile01"
                       aria-describedby="inputGroupFileAddon01">
                <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                <input asp-for="Document" />
            </div>
        </div>*@


        @*<div class="row">
            <div class="col-12">
                <div class="custom-file">
                    <div class="col-6">
                        <label asp-for="Document" class="form-control custom-file-input active"></label>@*These names come from our properties in the model *@
         @* <label class="custom-file-label">Choose File...</label>
                    </div>

                   <div class="col-6">
                        <input asp-for="Document" class="form-control" />
                        <span asp-validation-for="Document" class="text-danger"></span>
                    </div>
                    </div>
                    </div>
                    </div>*@

        <div class="row">
            <div class="col-12">
                <div class="file-upload-wrapper">
                    <input type="file" id="input-file-now-custom-1" class="file-upload" data-default-file="https://mdbootstrap.com/img/Photos/Others/images/89.webp" />
                </div>

                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Document" class="form-control" />
                        <span asp-validation-for="Document" class="text-danger"></span>

                    </div>
                    
                </div>
            </div>
        </div>

                    




    
    
</form>

@section Scripts{

    <script>
        $('.file-upload').file_upload();
    </script>
        

   @* <script>
        $(document).ready(function () {
            $('.costom-file-input').on("change", function () {
                var fileName = $(this).val().split("\\").pop();
                $(this).next('.custom-file-label').html(fileName);
            })
        })
    </script>*@



    }

Innovators/Views/Lecturer/Index.cshtml
@model IEnumerable<Innovators.Models.Task>
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Dashboard Template · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/dashboard/">

    

    

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }
      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    
    <!-- Custom styles for this template -->
@*    <link href="./css/Main.css" rel="stylesheet">
*@@*    <link href="./css/Style.css" rel="stylesheet">
*@
  </head>
  <body>
    <section class="hero">
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow ">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">Lecturer</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" asp-action="LecturerLogin"asp-controller="Home">Sign out</a>
    </div>
  </div>
</header>


        <div class="container p-3">
            <div class="row pt-4">
                <div class="col-6">
                    <h2 class="text-primary">TasKs</h2>
                </div>
                <div class="col-6 text-right">
                    <a asp-controller="Lecturer" asp-action="CreateTask" class="btn btn-primary">Create New Task</a>
                </div>
            </div>
            <br />

            @if (Model.Count() > 0)
            {
                <table class="table table-bordered table-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th>
                                Name
                            </th>
                            <th>
                                Description
                            </th>
                            <th>
                                Due Date
                            </th>
                            <th>
                                Status
                            </th>
                            <th>
                                File
</th>
<th>
</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var task in Model)
                        {
                            <tr>
                                <td width="30%">@task.TaskName</td>
                                <td width="30%">@task.TaskDescription</td>
                                <td width="30%">@task.DueDate</td>
                                <td width="30%">@task.Status</td>
                                <td width="30%">@task.Document</td>
                                <td>
                                    
</td>
                                <td width="30%">
                                    <div class="w-100 btn-group" role="group">
                                        <a asp-controller="Lecturer" asp-action="UpdateTask" asp-route-ID="@task.TaskId" class="btn btn-primary mx-1">Update</a>
                                        <a asp-controller="Lecturer" asp-action="DeleteTask" asp-route-ID="@task.TaskId" class="btn btn-danger mx-1">Delete</a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p>No Task created yet</p>
            }
        </div>








<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
              <span data-feather="home" class="align-text-bottom"></span>
             
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-action="Memo" asp-controller="Quiz">
              <span data-feather="file" class="align-text-bottom"></span>
              Memo
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart" class="align-text-bottom"></span>
              Mail box
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users" class="align-text-bottom"></span>
              Course Planning
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2" class="align-text-bottom"></span>
              Students
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers" class="align-text-bottom"></span>
              currrent activities
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted text-uppercase">
          <span>Tasks</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle" class="align-text-bottom"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" asp-action="Index" asp-controller="Quiz">
              <span data-feather="file-text" class="align-text-bottom"></span>
             New Quiz
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-action="Index" asp-controller="Register">
              <span data-feather="file-text"  class="align-text-bottom"></span>
              
              Daily Register
            </a>
          </li>

        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar" class="align-text-bottom"></span>
            This week
          </button>
        </div>
      </div>

      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

      <h2></h2>



                   









     @* <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
              <th scope="col">Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>text</td>
              <td>random</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>placeholder</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>placeholder</td>
              <td>tabular</td>
              <td>information</td>
              <td>irrelevant</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>random</td>
              <td>data</td>
              <td>placeholder</td>
              <td>text</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>placeholder</td>
              <td>irrelevant</td>
              <td>visual</td>
              <td>layout</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>data</td>
              <td>rich</td>
              <td>dashboard</td>
              <td>tabular</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>information</td>
              <td>placeholder</td>
              <td>illustrative</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>text</td>
              <td>placeholder</td>
              <td>layout</td>
              <td>dashboard</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>dashboard</td>
              <td>irrelevant</td>
              <td>text</td>
              <td>visual</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>dashboard</td>
              <td>illustrative</td>
              <td>rich</td>
              <td>data</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>random</td>
              <td>tabular</td>
              <td>information</td>
              <td>text</td>
            </tr>
          </tbody>
        </table>
      </div>*@

    </main>
  </div>
</div>
</section>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="dashboard.js"></script>
  </body>
</html>

Innovators/Views/Lecturer/Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="/css/style.min.css">
    <link rel="stylesheet" href="~/css/Main.css">

    <script defer src="/js/login.js"></script>
</head>
<body class="login">
    <div class="container">
        <h2 class="text-center">Login</h2>
        <br>
        <form action="/dashboard.html" class="loginForm">
            <div class="input-group">
                <label for="username" class="label">Username</label>
                <input type="text" id="username" class="input">
                <span class="error-message"></span>
            </div>
            <br>
            <div class="input-group">
                <label for="password" class="label">Password</label>
                <input type="password" id="password" class="input">
                <span class="error-message"></span>
            </div>
            <br>
            <button class="button" type="submit">Login</button>
        </form>
        
    </div>
    <a asp-action="Index" asp-controller="Lecturer">.</a>
</body>
</html>







@*@model Innovators.Models.Users
@{
    ViewData["Title"] = "Home Page";
}
<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3>Login</h3>
                @*<div class="d-flex justify-content-end social_icon">
                <span><i class="fab fa-facebook-square"></i></span>
                <span><i class="fab fa-google-plus-square"></i></span>
                <span><i class="fab fa-twitter-square"></i></span>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Login", "Lecturer", FormMethod.Post))
                {

                    if (ViewBag.LoginStatus != null)
                    {
                        if (ViewBag.LoginStatus == 0)
                        {
                            <div class="alert alert-danger">Invalid login detail</div>
                        }
                    }
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "username/Email" })

                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "password" })
                    </div>
                    <div class="row align-items-center remember">
                        <input type="checkbox">Remember Me
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Login" class="btn float-right login_btn">
                    </div>
                }
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center links">
                    Don't have an account?<a asp-action="Registration" asp-controller="Home">Sign Up</a>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="#">Forgot your password?</a>
                </div>
            </div>
        </div>
    </div>
</div>




<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Signin Template · Bootstrap v5.2</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/sign-in/">





<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }



      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="./css/SignIn.css" rel="stylesheet">
    <link href="./css/Main.css" rel="stylesheet">
    <link href="./css/Style.css" rel="stylesheet">

  </head>

  <body class="text-center">

<main class="form-signin w-100 m-auto">
  <form>
    <img class="mb-4" src="" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit"asp-controller="Lecturer"asp-action="Index">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2022</p>
  </form>
</main>

<

  </body>
</html>
*@

Innovators/Views/Lecturer/Success.cshtml
<h2>
    You have successfully Loged in!

</h2>
<a asp-action="Index" asp-controller="Lecturer" class="btn btn-success">Proceed</a>