Innovators/Models/AssignLecturer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Innovators.Models
{
    public class AssignLecturer
    {
        [Key]
        public int LecturerId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Surname { get; set; }
        [DisplayName("Email Address")]
        [Required]
        public string EmailAddress { get; set; }

        [Required]
        public string Course { get; set; }
        [Required]
        public string Module { get; set; }
        [DisplayName("Cell Number")]
        [Required]
        public string CellNumber { get; set; }
    }
}

Innovators/Models/CivilEngineering.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Innovators.Models
{
    public class CivilEngineering
    {
        [Key]
        public int ModuleId { get; set; }
        [DisplayName("Module")]
        public string ModuleName { get; set; }
        public string Course { get; set; }
        [DisplayName("Name")]
        public string StudentName { get; set; }
        [DisplayName("Surname")]
        public string StudentSurname { get; set; }
        [DisplayName("Student Number")]
        public int StudentNumber { get; set; }
        [DisplayName("Test 1")]
        public int Test1 { get; set; }
        [DisplayName("Test 2")]
        public int Test2 { get; set; }
        [DisplayName("Test 3")]
        public int Test3 { get; set; }
        public int Average { get; set; }
    }
}

Innovators/Models/InformationTechnology.cs
using System.ComponentModel.DataAnnotations;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace Innovators.Models
{
    public class InformationTechnology
    {
        [Key]
        public int ModuleId { get; set; }
        [DisplayName("Module")]
        public string ModuleName { get; set; }
        public string Course { get; set; }
        [DisplayName("Name")]
        public string StudentName { get; set; }
        [DisplayName("Surname")]
        public string StudentSurname { get; set; }
        [DisplayName("Student Number")]
        public int StudentNumber { get; set; }
        [DisplayName("Test 1")]
        public int Test1 { get; set; }
        [DisplayName("Test 2")]
        public int Test2 { get; set; }
        [DisplayName("Test 3")]
        public int Test3 { get; set; }
        public int Average { get; set; }
    }
}

Innovators/Models/Report.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;


namespace Innovators.Models
{
    public class Report
    {
        [Key]
        public int ModuleId { get; set; }
        [DisplayName("Module")]
        public string ModuleName { get; set; }
        public string Course { get; set; }
        [DisplayName("Name")]
        public string StudentName { get; set; }
        [DisplayName("Surname")]
        public string StudentSurname { get; set; }
        [DisplayName("Student Number")]
        public int StudentNumber { get; set; }
        [DisplayName("Test 1")]
        public int Test1 { get; set; }
        [DisplayName("Test 2")]
        public int Test2 { get; set; }
        [DisplayName("Test 3")]
        public int Test3 { get; set; }
        public int Average { get; set; }
    }
}

Innovators/Controllers/AssignLecturerController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;
using Innovators.Models;
using Innovators.Data;


namespace Innovators.Controllers
{
    public class AssignLecturerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        private readonly AppDbContext _db;
        public AssignLecturerController(AppDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult AssignLecturerDisplay()
        {
            IEnumerable<AssignLecturer> objList = _db.assignLecturers;
            return View(objList);
        }
        [HttpPost]
        public IActionResult AssignLecturerDisplay(AssignLecturer obj)
        {
            if (ModelState.IsValid)
            {
                _db.assignLecturers.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("AssignLecturerDisplay");
            }
            return View(obj);
        }
        public IActionResult UpdateLecturer(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.assignLecturers.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateLecturer(AssignLecturer obj)
        {
            _db.assignLecturers.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("AssignLecturerDisplay");
        }
        public IActionResult Update()
        {
            return View();
        }
    }
}

Innovators/Controllers/SubController.cs
using Innovators.Data;
using Innovators.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Web;
using System.Threading.Tasks;
using System.Text;


namespace Innovators.Controllers
{
    public class SubController : Controller
    {
        private readonly AppDbContext _db;
        public SubController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Sub()
        {
            return View();
        }
        public IActionResult Cal()
        {

            return View();
        }

        public IActionResult AssignLecturers()
        {
            return View();
        }


        //Civil Engineering

        //[HttpPost]
        //[HttpGet]
        public IActionResult CivilEngineering()
        {
            IEnumerable<CivilEngineering> objList = _db.civilEngineering;
            return View(objList);
        }
        [HttpGet]
        public IActionResult StudentProgress()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CivilEngineering(CivilEngineering obj)
        {
            if (ModelState.IsValid)//Checks to see if all the required fields have been met.
            {
                _db.civilEngineering.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("CivilEngineering");
            }
            return View(obj);
        }

        //Information Technology
        public IActionResult InformationTechnology()
        {
            IEnumerable<InformationTechnology> objList = _db.informationTechnology;
            return View(objList);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult InformationTechnology(InformationTechnology obj)
        {
            if (ModelState.IsValid)//Checks to see if all the required fields have been met.
            {
                _db.informationTechnology.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("InformationTechnology");
            }
            return View(obj);
        }
        //Report
        public IActionResult Report()
        {
            return View();
        }


    }
}

Innovators/Views/Sub/AssignLecturers.cshtml
@model Innovators.Models.AssignLecturer
@{
    ViewData["Title"] = "AssignLecturers";
}

<h1>AssignLecturers</h1>
<link rel="stylesheet" href="~/css/bootstrap.css" />

<form method="post" asp-action="AssignLecturers">
    <div class="border p-3">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Assign Lecturers</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <div class="col-4">
                            <label asp-for="Name"></label>
                        </div>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <div class="col-4">
                            <label asp-for="Surname"></label>
                        </div>
                        <input asp-for="Surname" class="form-control" />
                        <span asp-validation-for="Surname" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <div class="col-4">
                            <label asp-for="EmailAddress"></label>
                        </div>
                        <input asp-for="EmailAddress" class="form-control" />
                        <span asp-validation-for="EmailAddress" class="text-danger"></span>
                    </div>
                    <div class="col-4">

                        <div class="col-4">
                            <label asp-for="Course"></label>
                        </div>
                        <input asp-for="Course" class="form-control" />
                        <span asp-validation-for="Course" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <div class="col-4">
                            <label asp-for="Module"></label>
                        </div>
                        <input asp-for="Module" class="form-control" />
                        <span asp-validation-for="Module" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <div class="col-4">
                            <label asp-for="CellNumber"></label>
                        </div>
                        <input asp-for="CellNumber" class="form-control" />
                        <span asp-validation-for="CellNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Create" asp-controller="AssignLecturer" asp-action="AssignLecturerDisplay" />
                        </div>
                        <div class="col">
                            <a asp-area="" asp-action="AssignLecturerDisplay" asp-controller="AssignLecturer" class="btn btn-danger w-75">Back</a>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

Innovators/Views/Sub/Cal.cshtml
@{
    ViewData["Title"] = "Cal";
}

<!doctype html>
<html lang="en">
  <head>
  	<title>Schedule Meetings</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	@*<link rel="stylesheet" href="css/style.css">*@
	<link rel="stylesheet" href="~/calender/css/style.css" />
	<link rel="stylesheet" href="~/css/bootstrap.css" />

	</head>
	<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h1 class="heading-section">Schedule Meetings</h1>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="content w-100">
				    <div class="calendar-container">
				      <div class="calendar"> 
				        <div class="year-header"> 
				          <span class="left-button fa fa-chevron-left" id="prev"> </span> 
				          <span class="year" id="label"></span> 
				          <span class="right-button fa fa-chevron-right" id="next"> </span>
				        </div> 
				        <table class="months-table w-100"> 
				          <tbody>
				            <tr class="months-row">
				              <td class="month">Jan</td> 
				              <td class="month">Feb</td> 
				              <td class="month">Mar</td> 
				              <td class="month">Apr</td> 
				              <td class="month">May</td> 
				              <td class="month">Jun</td> 
				              <td class="month">Jul</td>
				              <td class="month">Aug</td> 
				              <td class="month">Sep</td> 
				              <td class="month">Oct</td>          
				              <td class="month">Nov</td>
				              <td class="month">Dec</td>
				            </tr>
				          </tbody>
				        </table> 
				        
				        <table class="days-table w-100"> 
				          <td class="day">Sun</td> 
				          <td class="day">Mon</td> 
				          <td class="day">Tue</td> 
				          <td class="day">Wed</td> 
				          <td class="day">Thu</td> 
				          <td class="day">Fri</td> 
				          <td class="day">Sat</td>
				        </table> 
				        <div class="frame"> 
				          <table class="dates-table w-100"> 
			              <tbody class="tbody">             
			              </tbody> 
				          </table>
				        </div> 
				        <button class="button" id="add-button">Add Event</button>
				      </div>
				    </div>
				    <div class="events-container">
				    </div>
				    <div class="dialog" id="dialog">
				        <h2 class="dialog-header"> Add New Event </h2>
				        <form class="form" id="form">
				          <div class="form-container" align="center">
				            <label class="form-label" id="valueFromMyButton" for="name">Event name</label>
				            <input class="input" type="text" id="name" maxlength="36">
							<label class="form-label" id="valueFromMyButton" for="name">Agenda</label>
							<input class="input" type="text" id="name" maxlength="36">
				            <label class="form-label" id="valueFromMyButton" for="count">Number of people to invite</label>
				            <input class="input" type="number" id="count" min="0" max="1000000" maxlength="7">
				            <input type="button" value="Cancel" class="button" id="cancel-button">
				            <input type="button" value="OK" class="button button-white" id="ok-button">
				          </div>
				        </form>
				      </div>
				  </div>
				</div>
			</div>
		</div>
	</section>

	<script src="~/calender/js/jquery.min.js"></script>
	<script src="~/calender/js/popper.js"></script>
	<script src="~/calender/js/bootstrap.min.js"></script>
	<script src="~/calender/js/main.js"></script>
	</body>
	<div class="row pt-4">
    <div class="col-6 text-left">
        <a asp-controller="Sub" asp-action="Sub" class="btn btn-danger" type="button">Back</a>
    </div>

</div
</html>

Innovators/Views/Sub/CivilEngineering.cshtml
<link rel="stylesheet" href="~/css/bootstrap.css" />
@model IEnumerable<Innovators.Models.CivilEngineering>
@{
    ViewData["Title"] = "CivilEngineering";
}

<h1>CivilEngineering</h1>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Subject Coordinators List</h2>
        </div>
        @*<div class="col-6 text-right">
        <a asp-controller="SubController" asp-action="AddCoordinator" class="btn btn-primary">Add New Coordinator</a>
        </div>*@
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Module
                    </th>
                    <th>
                        Course
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Surname
                    </th>
                    <th>
                        Student Number
                    </th>
                    <th>
                        Test 1
                    </th>
                    <th>
                        Test 2
                    </th>
                    <th>
                        Test 3
                    </th>
                    <th>
                        Average
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var add in Model)
                {
                    <tr>
                        <td width="30%">@add.ModuleName</td>
                        <td width="30%">@add.Course</td>
                        <td width="30%">@add.StudentName</td>
                        <td width="30%">@add.StudentSurname</td>
                        <td width="30%">@add.StudentNumber</td>
                        <td width="30%">@add.Test1</td>
                        <td width="30%">@add.Test2</td>
                        <td width="30%">@add.Test3</td>
                        <td width="30%">@add.Average</td>


                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Coordinator added</p>
    }
</div>
<div class="row pt-4">
    <div class="col-6 text-left">
        <a asp-controller="Sub" asp-action="StudentProgress" class="btn btn-danger" type="button">Back</a>
    </div>

</div>

Innovators/Views/Sub/InformationTechnology.cshtml
<link rel="stylesheet" href="~/css/bootstrap.css" />
@model IEnumerable<Innovators.Models.InformationTechnology>
@{
    ViewData["Title"] = "InformationTechnology";
}

<h1>InformationTechnology</h1>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Subject Coordinators List</h2>
        </div>
        @*<div class="col-6 text-right">
        <a asp-controller="SubController" asp-action="AddCoordinator" class="btn btn-primary">Add New Coordinator</a>
        </div>*@
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Module
                    </th>
                    <th>
                        Course
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Surname
                    </th>
                    <th>
                        Student Number
                    </th>
                    <th>
                        Test 1
                    </th>
                    <th>
                        Test 2
                    </th>
                    <th>
                        Test 3
                    </th>
                    <th>
                        Average
                    </th>
                </tr>
            </thead>

            <tbody>
                @foreach (var add in Model)
                {
                    <tr>
                        <td width="30%">@add.ModuleName</td>
                        <td width="30%">@add.Course</td>
                        <td width="30%">@add.StudentName</td>
                        <td width="30%">@add.StudentSurname</td>
                        <td width="30%">@add.StudentNumber</td>
                        <td width="30%">@add.Test1</td>
                        <td width="30%">@add.Test2</td>
                        <td width="30%">@add.Test3</td>
                        <td width="30%">@add.Average</td>


                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Coordinator added</p>
    }
</div>
<div class="row pt-4">
    <div class="col-6 text-left">
        <a asp-controller="Sub" asp-action="StudentProgress" class="btn btn-danger" type="button">Back</a>
    </div>

</div>

Innovators/Views/Sub/Report.cshtml
@{
    ViewData["Title"] = "Report";
}

<h1>Report</h1>
<link rel="stylesheet" href="~/css/bootstrap.css" />
<!DOCTYPE html>
<html>
<head>
    <title>Report</title>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <meta name="robots" content="noindex">
    <link rel="stylesheet" href="kiosk.css" type="text/css">
    <script language="JavaScript">
                <!--
        function MM_goToURL() { //v3.0
            var i, args = MM_goToURL.arguments; document.MM_returnValue = false;
            for (i = 0; i < (args.length - 1); i += 2) eval(args[i] + ".location='" + args[i + 1] + "'");
        }

        function NMM_goToURL() { //v3.0
            var i, args = NMM_goToURL.arguments; document.NMM_returnValue = false;
            for (i = 0; i < (args.length - 1); i += 2) eval(args[i] + ".location='" + args[i + 1] + "'");
            alert('This report has been printed. Please wait for it to emerge from the printer slot.');
        }


        //-->
    </script>
</head>
<div id="parentDiv" style="width:500px">
    <body bgcolor="#FFFFFF" text="#000000">
        <table width="100%" border="0">
            <tr>

                <td class="main_header">Student Report</td>
                <td width="120px" align="right"></td>
            </tr>
            <tr>
                <td colspan="2"><h3 class="mid_header">Examination Results </h3></td>
                <td align="right"><input type="button" name="Button" value="Back" onClick="history.back()" class="back_button"></td>

            </tr>
        </table>

        <table border="0">
            <tr height="1px" class="table_divline">
                <td height="1px" colspan="100"></td>
            </tr>
            <tr><td class="table_header">Name</td><td class="table_cell_even" colspan="5">Bathini</td></tr>
            <tr><td class="table_header">Surname</td><td class="table_cell_even" colspan="5">Buso</td></tr>
            <tr><td class="table_header">Student No.</td><td class="table_cell_even" colspan="5">223465789</td></tr>
            <tr><td class="table_header">Course</td><td class="table_cell_even" colspan="5">Information Technology</td></tr>

            <tr height="1px" class="table_divline">
                <td height="1px" colspan="100"></td>
            </tr>
            <tr>
                <td class="table_header" width="80">Module</td>
                <td class="table_header" width="80">Course</td>
                <td class="table_header" width="80">Name</td>
                <td class="table_header" width="80">Surname</td>
                <td class="table_header" width="80">Student Number</td>
                <td class="table_header" width="100">Test 1</td>
                <td class="table_header" width="80">Test 2</td>
                <td class="table_header" width="80">Test 3</td>
                <td class="table_header" width="80">Average</td>
            </tr>
            <tr height="1px" class="table_divline">
                <td height="1px" colspan="100"></td>
            </tr>
            <tr class="table_cell_even"><td>Programming</td><td>Infomation Technology</td><td>Bathini</td><td>Buso</td><td>223465789</td><td></td><td>60</td><td>80</td><td>67</td><td>69</td></tr>

            <!--
                <p class="normal_text">PLEASE NOTE:  </p>
                <p class="normal_text">Provisional Examination Results will be published on 27 June 2014 at the end of the day.</p>
                <p class="normal_text">Re-Examination Time-table will be published on 7 July 2014 at the end of the day.</p>
                <p class="normal_text">All students qualifying for Last Outstanding Examinations will be published on 7 July 2014 at the end of the day.</p>
                <p class="normal_text">&#8226;    Should you be of the opinion that you should qualify and it is not indicated as such at this date, please contact your Faculty Admin staff member on 8 July 2014 only.</p>
                //-->

    </body>
</html>
<a href="javascript:generatePDF()" id="downloadButton">Click to download</a>
</div>
<script>
    async function generatePDF() {
        document.getElementById("downloadButton").innerHTML = "";

        //Downloading
        var downloading = document.getElementById("parentDiv");
        var doc = new jsPDF('p', 'pt', 'a4');

        await html2canvas(downloading, {
            allowTaint: true,
            useCORS: true,
            width: 2000
        }).then((canvas) => {
            //Canvas (convert to PNG)
            doc.addImage(canvas.toDataURL("pdf/pdf"), 'PDF', 0, 0, 1500, 200);
        })

        doc.save("ProgressReport.pdf");

        //End of downloading

        document.getElementById("downloadButton").innerHTML = "";
    }
</script>

Innovators/Views/Sub/StudentProgress.cshtml
<link rel="stylesheet" href="~/css/bootstrap.css" />
@{
    ViewData["Title"] = "StudentProgress";
}

<h1>StudentProgress</h1>

<div>
    <div class="col-6 text-left">
        <a asp-controller="Sub" asp-action="InformationTechnology" class="btn btn-primary">Information Technology</a>
    </div>

    <div class="col-6 text-left">
        <a asp-controller="Sub" asp-action="CivilEngineering" class="btn btn-primary">Civil Engineering</a>
    </div>

    <div class="col-6 text-left">
        <a asp-controller="Sub" asp-action="Sub" class="btn btn-primary">Back</a>
    </div>

</div>

Innovators/Views/Sub/Sub.cshtml
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8" />
    <title>Subject Coordinator Dashboard</title>
    <link rel="stylesheet" href="~/css/Sub.css" />
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/prism-okaidia.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

</head>
<body>

    <div class="sidebar">
        <div class="logo-details">
            <i class='bx bxl-c-plus-plus '></i>
            <span class="log_name">iTutor</span>
        </div>
        <ul class="nav-links">
            <li>
                <a href="">
                    <i class='bx bxs-grid-alt'></i>
                    <span class="link_name">Dashboard</span>

                </a>
            </li>
            <li>
                <a asp-controller="AssignLecturer" asp-action="AssignLecturerDisplay">
                    <i class='bx bxs-graduation'></i>
                    <span class="link_name">Lecturers</span>

                </a>
            </li>
            <li>
                <a asp-controller="Sub" asp-action="Cal">
                    <i class='bx bxs-message-dots'></i>
                    <span class="link_name">Schedule Meetings</span>

                </a>

            </li>

            <li>
                <a asp-controller="Sub" asp-action="StudentProgress">
                    <i class='bx bx-book-open'></i>
                    <span class="link_name">Student Progress</span>

                </a>
            </li>
            <li>
                <a asp-controller="Home" asp-action="Index" class="nav-link">
                    <i class="bx bx-log-out icon"></i>
                    <span class="link">Logout</span>
                </a>
            </li>

        </ul>

    </div>

    <!-- home-content -->
    <section class="home-section">
        <nav>
            <div class="sidebar-button">
                <i class='bx bx-menu sidebarBtn'></i>
                <span class="dashboard">Dashboard </span>
            </div>
            <div class="search-box">
                <input type="text" placeholder="Search..." />
                <i class='bx bx-search'></i>
            </div>
            <div class="profile-details">
                <img src="~/Images/IMG_20211030_202641_729.webp" alt="">
                <span class="subject_coordinator_name">Chuma Mhaga</span>
                <i class='bx bx-chevron-down'></i>
            </div>
        </nav>
        <!-- home-content -->
        <div class="home-content">
            <div class="overview-boxes">
                <div class="box">
                    <div class="left-side">
                        <div class="box_topic">Reports</div>
                        <div class="number"></div>
                        <div class="indicator">
                            <i class='bx bxs-up-arrow-alt'></i>
                            <span class="text">Up from yesterday</span>
                        </div>
                    </div>
                    <a asp-controller="Sub" asp-action="Report">
                        <i class='bx bx-show-alt show'></i>

                    </a>

                </div>
                <div class="box">
                    <div class="left-side">
                        <div class="box_topic">Schedule Meetings</div>
                        <div class="number"></div>
                        <div class="indicator">
                            <i class='bx bxs-up-arrow-alt'></i>
                            <span class="text">Up from yesterday</span>
                        </div>
                    </div>
                    <a asp-controller="Sub" asp-action="Cal">

                        <i class='bx bx-show-alt show two'></i>
                    </a>


                </div>
                <div class="box">
                    <div class="left-side">
                        <div class="box_topic">Lecturers</div>
                        <div class="number"></div>
                        <div class="indicator">
                            <i class='bx bxs-up-arrow-alt'></i>
                            <span class="text">Up from yesterday</span>
                        </div>
                    </div>
                    <a asp-controller="AssignLecturer" asp-action="AssignLecturerDisplay">

                        <i class='bx bx-show-alt show three'></i>
                    </a>
                </div>
                <div class="box">
                    <div class="left-side">
                        <div class="box_topic">Students</div>
                        <div class="number"></div>
                        <div class="indicator">
                            <i class='bx bxs-up-arrow-alt'></i>
                            <span class="text">Up from yesterday</span>
                        </div>
                    </div>

                    <a asp-controller="Sub" asp-action="StudentProgress">
                        <i class='bx bx-show-alt show four'></i>
                    </a>
                </div>

            </div>


    </section>
    <script src="~/js/script.js"></script>
    <script src="~/js/prism.js"></script>
</body>


</html>